### ISSUE TITLE
想问一下数据集的csv文件的格式是什么样的？

### ISSUE THREAD

**Issue by LioneWang** [Retinal-Research/REDOT#1]

**Comment by ChongQingNoSubway** [comment]
原始EyeQ数据集CSV包括两个label, 一是quality label(reject, usable, accept), 其他一个是Diabetic retinopathy grading label(有5个level从normal到严重). 
下载 CSV: https://github.com/HzFu/EyeQ
数据集是 EYEPACS: https://www.kaggle.com/c/diabetic-retinopathy-detection/data

**Comment by LioneWang** [comment]
好的谢谢！在想请问一下作者，我通过代码分析了解到您的代码中是采用了EyeQ的csv文件读取，请问如果想用idrid数据集在您的模型中进行验证的话，对idrid数据集的csv文件处理应该如何处理呢？（在您的代码中好像只有对EyeQ数据集的处理过程）

**Comment by ChongQingNoSubway** [comment]
idrid有质量标签吗？ 我不确定你需要做一个怎样的下游任务. 
你可以先下载eyeQ的 CSV进行查看, 构造一个类似的CSV是可行的. 
如果只是单纯的增强效果的检查，你可以直接把图片给chechpoint，在dataloader那里改一下只返回图片然后直接推理就可以了， 这个过程你只需要构造一个CSV包括所有你自己的图片就可以了.

**Comment by ChongQingNoSubway** [comment]
idrid有质量标签吗？ 我不确定你需要做一个怎样的下游任务.
你可以先下载eyeQ的 CSV进行查看, 构造一个类似的CSV是可行的.
如果只是单纯的增强效果的检查，你可以直接把图片给checkpoint，在dataloader那里改一下只返回图片然后直接推理就可以了， 这个过程你只需要构造一个CSV包括所有你自己的图片就可以了,不需要任何标签（dataloader中读取标签的代码直接注释就好了）.
